CC=gcc
CFLAGS=-O2 -m32 -Wall -Wextra -Werror -Wshadow -std=c99 -fwrapv
OUTFLAG=-o

ALL:
	$(CC) $(CFLAGS) euler_problem_1.c $(OUTFLAG) euler_prob_1.out
	$(CC) $(CFLAGS) euler_problem_2.c $(OUTFLAG) euler_prob_2.out
	$(CC) $(CFLAGS) euler_problem_4.c $(OUTFLAG) euler_prob_4.out
	$(CC) $(CFLAGS) euler_problem_5.c $(OUTFLAG) euler_prob_5.out
	$(CC) $(CFLAGS) euler_problem_8.c $(OUTFLAG) euler_prob_8.out
	$(CC) $(CFLAGS) euler_problem_16.c $(OUTFLAG) euler_prob_16.out
